# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [5]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [4]:
print("NumPy version: ", np.__version__)

NumPy version:  2.0.2


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [10]:
rng = np.random.default_rng()

In [25]:
a = rng.random((2,3,5))
# create array
# 2 blocks, 3 rows, 5 columns


### 4. Print a.


In [26]:
print(a)

[[[0.51788491 0.58364023 0.90035508 0.53831641 0.21017883]
  [0.83150338 0.22623934 0.29809304 0.87303894 0.25862823]
  [0.28581552 0.4630904  0.92774794 0.21032976 0.11541829]]

 [[0.78243849 0.61935865 0.82756722 0.80212271 0.91862925]
  [0.70996888 0.76613905 0.2855422  0.7913012  0.14277374]
  [0.18479105 0.50463638 0.30499413 0.57089288 0.64888573]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [42]:
b = rng.integers(1, 2, size=(5, 2, 3))


### 6. Print b.


In [43]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [34]:
np.array_equal(a, b)

False


### 8. Are you able to add a and b? Why or why not?


In [79]:
np.concatenate((a, b), axis = 0)

# doesn't have the same structure, so it can't be added

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [46]:
c = np.transpose(b, (1, 2, 0))
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [80]:
d = np.add(a, c)


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [81]:
print(a)
print(d)



[[[0.51788491 0.58364023 0.90035508 0.53831641 0.21017883]
  [0.83150338 0.22623934 0.29809304 0.87303894 0.25862823]
  [0.28581552 0.4630904  0.92774794 0.21032976 0.11541829]]

 [[0.78243849 0.61935865 0.82756722 0.80212271 0.91862925]
  [0.70996888 0.76613905 0.2855422  0.7913012  0.14277374]
  [0.18479105 0.50463638 0.30499413 0.57089288 0.64888573]]]
[[[1.51788491 1.58364023 1.90035508 1.53831641 1.21017883]
  [1.83150338 1.22623934 1.29809304 1.87303894 1.25862823]
  [1.28581552 1.4630904  1.92774794 1.21032976 1.11541829]]

 [[1.78243849 1.61935865 1.82756722 1.80212271 1.91862925]
  [1.70996888 1.76613905 1.2855422  1.7913012  1.14277374]
  [1.18479105 1.50463638 1.30499413 1.57089288 1.64888573]]]



### 12. Multiply a and c. Assign the result to e.


In [82]:
e = np.multiply(a, c)



### 13. Does e equal to a? Why or why not?


In [83]:
print(e)
print(a)

# yes, they are the same

[[[0.51788491 0.58364023 0.90035508 0.53831641 0.21017883]
  [0.83150338 0.22623934 0.29809304 0.87303894 0.25862823]
  [0.28581552 0.4630904  0.92774794 0.21032976 0.11541829]]

 [[0.78243849 0.61935865 0.82756722 0.80212271 0.91862925]
  [0.70996888 0.76613905 0.2855422  0.7913012  0.14277374]
  [0.18479105 0.50463638 0.30499413 0.57089288 0.64888573]]]
[[[0.51788491 0.58364023 0.90035508 0.53831641 0.21017883]
  [0.83150338 0.22623934 0.29809304 0.87303894 0.25862823]
  [0.28581552 0.4630904  0.92774794 0.21032976 0.11541829]]

 [[0.78243849 0.61935865 0.82756722 0.80212271 0.91862925]
  [0.70996888 0.76613905 0.2855422  0.7913012  0.14277374]
  [0.18479105 0.50463638 0.30499413 0.57089288 0.64888573]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [84]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.9277479410481635 1.1154182856782566 1.5366773951083974



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [75]:
f = np.empty((2, 3, 5))
print(f)

# is not really empty
# doesn't fill with zeros, takes raw memory which is the ram
# totally random

[[[0.51788491 0.58364023 0.90035508 0.53831641 0.21017883]
  [0.83150338 0.22623934 0.29809304 0.87303894 0.25862823]
  [0.28581552 0.4630904  0.92774794 0.21032976 0.11541829]]

 [[0.78243849 0.61935865 0.82756722 0.80212271 0.91862925]
  [0.70996888 0.76613905 0.2855422  0.7913012  0.14277374]
  [0.18479105 0.50463638 0.30499413 0.57089288 0.64888573]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [85]:
for i in range(d.shape[0]):
  for j in range(d.shape[1]):
    for k in range(d.shape[2]):
      value = d[i, j, k]

      if value == d_min:
        f[i, j, k] = 0
      elif value == d_max:
        f[i, j, k] = 100
      elif value == d_mean:
        f[i, j, k] = 50
      elif d_min < value < d_mean:
        f[i, j, k] = 25
      elif d_mean < value < d_max:
        f[i, j, k] = 75






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [87]:
print(d)

[[[1.51788491 1.58364023 1.90035508 1.53831641 1.21017883]
  [1.83150338 1.22623934 1.29809304 1.87303894 1.25862823]
  [1.28581552 1.4630904  1.92774794 1.21032976 1.11541829]]

 [[1.78243849 1.61935865 1.82756722 1.80212271 1.91862925]
  [1.70996888 1.76613905 1.2855422  1.7913012  1.14277374]
  [1.18479105 1.50463638 1.30499413 1.57089288 1.64888573]]]


In [86]:
print(f)

[[[ 25.  75.  75.  75.  25.]
  [ 75.  25.  25.  75.  25.]
  [ 25.  25. 100.  25.   0.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25.  25.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
### [your code here]